### PR TITLE
Upgrade to Dotty 0.19.0-RC1

### LINKED ISSUE #30: Upgrade to dotty 0.19.0-RC1

### PR DESCRIPTION
**Pull request by bishabosha**
fixes #30 

It compiles and passes the tests

Note: `intent.formatters.FormatTest::'supports Try-Failure'` failed to infer the implicit so I added an explicit type parameter of `Try[Int]`

Also I removed the ClassTag parameter from the given for `TryFmt[TInner, T]`, which I assume was added just to keep them as anonymous

### CODE REVIEW

**Comment by provegard** [comment]
Very nice! I opened the code in my now restored editor and it works just fine. When I tried the upgrade before I had a christmas tree of errors...

I will take a look at the changes you did. If I remove `ClassTag` from `TryFmt` with 0.18.1, I get

image

with:

```
cannot merge
  method Formatter_T_given in trait FormatterGivens of type [TInner, T <: util.Try[TInner]]
   given (x$1: intent.core.Formatter[TInner]): intent.core.Formatter[T]  and
  method Formatter_T_given in trait FormatterGivens of type [TInner, T <: Option[TInner]]
   given (x$1: intent.core.Formatter[TInner]): intent.core.Formatter[T]
they are both defined in trait FormatterGivens but have matching signatures
  [TInner, T <: util.Try[TInner]]
   given (x$1: intent.core.Formatter[TInner]): intent.core.Formatter[T] and
  [TInner, T <: Option[TInner]]
   given (x$1: intent.core.Formatter[TInner]): intent.core.Formatter[T]
as members of trait FormatterGivens
```

So I suppose there are some improvements in 0.19.0 that make this error go away...

Thank you for your help!

**Comment by bishabosha** [comment]
The error still appears in 0.19, but really its masking the fact that the anonymous givens have the same generated name, so I gave them sensible names, but that may be against your style, so that can be reverted easily

**Comment by provegard** [comment]
Aha, I see. No, using sensible names is better than adding ClassTags, I think. 

We're doing this project partly to explore/learn Dotty, so we don't really have a preferred style yet.

**Comment by bishabosha** [comment]
This is nice work, perhaps it could be added to the community build?

**Comment by provegard** [comment]
Thank you! 

Yes, that'd be great. I suppose we just follow the instructions at https://github.com/lampepfl/dotty/tree/master/community-build/test/scala/dotty/communitybuild ?

**Comment by bishabosha** [comment]
Yes thats correct, and then the test runner just calls whatever sbt commands you need to compile all the sources and then optionally test the runtime behaviour of your project.

**Comment by provegard** [comment]
I still have problems with the editor, it seems. Out of curiosity, I removed the option `-Yindent-colons` which you added. A subseqent compilation resulted in 45 errors, the first in `future.scala`. I then opened the editor using `launchIDE`. No errors in `future.scala`. I removed the eol colon on line 19. _Now_ the editor starts showing errors, the first on `given` inside of the parentheses on line 10. If I move `given` outside of the parentheses, the editor is happy.

So it seems my editor is severely out of sync. I will try reinstalling the Scala and Dotty plugins again to see if that helps.

**Comment by provegard** [comment]
Ok, `-Yindent-colons` appears to be required for consistency between compiler and editor.

**Comment by bishabosha** [comment]
I think i might know your problem, if you do not clean your project, and a compilation fails, but there already exist `.dotty-ide-artifact` and `.dotty-ide.json` files in the project root then the previously compiled code and settings are used in the editor.

**Comment by provegard** [comment]
Thanks, I'll add those files to the `clean` task for now.

**Pull request merged**
